services:
  app:
    build:
      context: .
      dockerfile: serverconfig/Dockerfile
    image: taut0logy/eksathe-app:latest
    container_name: eksathe_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html/public:cached
      - ./storage:/var/www/html/storage:cached
      - ./bootstrap/cache:/var/www/html/bootstrap/cache:cached
    depends_on:
      - db
      - garage
    networks:
      - eksathe-net

  nginx:
    image: nginx:1.26
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage/app/public:/var/www/html/storage/app/public:ro
      - ./serverconfig/nginx.conf:/etc/nginx/conf.d/default.conf
      # TLS certs (uncomment and adjust paths if using SSL)
      # - /etc/letsencrypt/live/eksathe.taut0logy.tech/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      # - /etc/letsencrypt/live/eksathe.taut0logy.tech/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app
    networks:
      - eksathe-net

  db:
    image: mysql:8.0
    container_name: eksathe_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-rootpassword}"
      MYSQL_DATABASE: "${DB_DATABASE:-eksathe}"
      MYSQL_USER: "${DB_USERNAME:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-laravelpassword}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - eksathe-net

  garage:
    image: dxflrs/garage:v2.1.0
    container_name: garaged
    restart: unless-stopped
    volumes:
      - ./serverconfig/garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900" # s3 api
      - "3901:3901" # rpc
      - "3902:3902" # web
      - "3903:3903" # admin
    networks:
      - eksathe-net

  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: garage_webui
    restart: unless-stopped
    volumes:
      - ./serverconfig/garage.toml:/etc/garage.toml:ro
    ports:
      - "3909:3909"
    depends_on:
      - garage
    networks:
      - eksathe-net

volumes:
  db_data:
  garage_meta:
  garage_data:

networks:
  eksathe-net:
    driver: bridge
