version: "3.8"

services:
  eksathe-app:
    build:
      context: .
      dockerfile: serverconfig/app.Dockerfile
    container_name: eksathe-app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=eksathe
      - DB_USERNAME=eksathe
      - DB_PASSWORD=secret
    depends_on:
      - eksathe-db
    restart: always
    networks:
      - eksathe-network

  eksathe-server:
    image: nginx:latest
    container_name: eksathe-server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./serverconfig/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - eksathe-app
    restart: always
    networks:
      - eksathe-network

  eksathe-db:
    image: mysql:8
    container_name: eksathe-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eksathe
      MYSQL_USER: eksathe
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - eksathe-network

volumes:
  db_data:

networks:
  eksathe-network:
    driver: bridge
