name: CI/CD Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eksathe-app:latest .

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/eksathe-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_SERVER_USER }}
          password: ${{ secrets.CLOUD_SERVER_PASSWORD }}
          script: |
            # Create Docker network if it doesn't exist
            docker network create eksathe-network || true

            # Stop and remove existing containers
            docker stop eksathe-db || true
            docker rm eksathe-db || true
            docker stop eksathe-app || true
            docker rm eksathe-app || true

            # Pull latest images
            docker pull mysql:8
            docker pull ${{ secrets.DOCKER_USERNAME }}/eksathe-app:latest

            # Remove dangling images
            docker image prune -f || true

            # Run MySQL container
            docker run -d \
              --name eksathe-db \
              -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              -e MYSQL_DATABASE=eksathe \
              -e MYSQL_USER=eksathe \
              -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -v db_data:/var/lib/mysql \
              --network eksathe-network \
              mysql:8

            # Run app container
            docker run -d \
              --name eksathe-app \
              -p 80:80 \
              -e APP_KEY=${{ secrets.APP_KEY }} \
              -e APP_ENV=production \
              -e APP_DEBUG=true \
              -e APP_URL=${{ secrets.APP_URL }} \
              -e DB_HOST=eksathe-db \
              -e DB_PORT=3306 \
              -e DB_DATABASE=eksathe \
              -e DB_USERNAME=eksathe \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e MAIL_MAILER=smtp \
              -e MAIL_HOST=smtp.gmail.com \
              -e MAIL_PORT=587 \
              -e MAIL_USERNAME=${{ secrets.MAIL_ADDRESS }} \
              -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
              -e MAIL_ENCRYPTION=tls \
              -e MAIL_FROM_ADDRESS=${{ secrets.MAIL_ADDRESS }} \
              -e REVERB_APP_KEY=${{ secrets.REVERB_APP_KEY }} \
              -e REVERB_APP_SECRET=${{ secrets.REVERB_APP_SECRET }} \
              -e REVERB_HOST="${{ secrets.REVERB_HOST }}" \
              -e REVERB_PORT=8081 \
              -e REVERB_SERVER_PORT=8082 \
              --network eksathe-network \
              ${{ secrets.DOCKER_USERNAME }}/eksathe-app:latest

            # Remove dangling images
            docker image prune -f || true

            # Remove dangling volumes
            docker volume prune -f || true

            # Wait for the Laravel container to be ready (use a better approach for waiting)
            echo "Waiting for the Laravel container to be ready..."
            counter=0
            until docker exec eksathe-app ls public/build || [ $counter -ge 100 ]; do
              echo "Laravel container is not ready yet... (attempt $counter/100)"
              counter=$((counter + 1))
              sleep 3
            done
            
            if [ $counter -ge 100 ]; then
              echo "Error: Timed out waiting for Laravel container after 5 minutes"
              exit 1
            fi

            # Link Storage
            echo "Linking Storage..."
            docker exec eksathe-app php artisan storage:link

            # Optimize
            # echo "Optimizing..."
            # docker exec eksathe-app php artisan optimize

            # Check Frontend build
            echo "Checking Frontend build..."
            docker exec eksathe-app ls public/build
            docker exec eksathe-app ls public/build/assets

            # Wait for the MySQL container to be ready
            echo "Waiting for MySQL to be ready..."
            until docker exec eksathe-db mysqladmin ping --silent; do
              echo "MySQL is not ready yet..."
              sleep 3
            done

            # Run Migrations
            echo "Running Migrations..."
            docker exec eksathe-app php artisan migrate:fresh --force

            # Clear Cache
            echo "Clearing Cache..."
            docker exec eksathe-app php artisan cache:clear
            docker exec eksathe-app php artisan config:clear
            docker exec eksathe-app php artisan route:clear

            # Cache Config, routes and views
            echo "Caching Config, routes and views..."
            docker exec eksathe-app php artisan config:cache
            docker exec eksathe-app php artisan route:cache
            docker exec eksathe-app php artisan view:cache

            # Restart container
            echo "Restarting container..."
            docker stop eksathe-app
            docker start eksathe-app

            # Check nginx configuration
            echo "Checking nginx configuration..."
            docker exec eksathe-app nginx -t

            # Check Container log
            echo "Checking Container Logs..."
            docker logs eksathe-app

            # Check nginx log
            echo "Checking nginx error log..."
            docker exec eksathe-app cat /var/log/nginx/error.log

            # Check laravel log
            echo "Checking Laravel log..."
            docker exec eksathe-app cat storage/logs/laravel.log
